name: "particlenet_AK4_ragged"
platform: "onnxruntime_onnx"
max_batch_size : 50
dynamic_batching {
   preferred_batch_size: [ 4, 8, 16 ]
   max_queue_delay_microseconds: 200
}
input [
  {
    name: "pf_points"
    data_type: TYPE_FP32
    dims: [ -1 ]
    allow_ragged_batch: true
  },
  {
    name: "pf_features"
    data_type: TYPE_FP32
    dims: [ -1 ]
    allow_ragged_batch: true
  },
  {
    name: "pf_mask"
    data_type: TYPE_FP32
    dims: [ -1 ]
    allow_ragged_batch: true
  },
  {
    name: "sv_points"
    data_type: TYPE_FP32
    dims: [ -1 ]
    allow_ragged_batch: true
  },
  {
    name: "sv_features"
    data_type: TYPE_FP32
    dims: [ -1 ]
    allow_ragged_batch: true
  },
  {
    name: "sv_mask"
    data_type: TYPE_FP32
    dims: [ -1 ]
    allow_ragged_batch: true
  },
  {
    name: "batch_shapes_pf_points"
    data_type: TYPE_INT32
    dims: [ -1 ]
    allow_ragged_batch: true
  },
  {
    name: "batch_shapes_pf_features"
    data_type: TYPE_INT32
    dims: [ -1 ]
    allow_ragged_batch: true
  },
  {
    name: "batch_shapes_pf_mask"
    data_type: TYPE_INT32
    dims: [ -1 ]
    allow_ragged_batch: true
  },
  {
    name: "batch_shapes_sv_points"
    data_type: TYPE_INT32
    dims: [ -1 ]
    allow_ragged_batch: true
  },
  {
    name: "batch_shapes_sv_features"
    data_type: TYPE_INT32
    dims: [ -1 ]
    allow_ragged_batch: true
  },
  {
    name: "batch_shapes_sv_mask"
    data_type: TYPE_INT32
    dims: [ -1 ]
    allow_ragged_batch: true
  },
]
optimization {
  graph {
    level: -1
  }
}
output [
  {
    name: "softmax"
    data_type: TYPE_FP32
    dims: [ -1, 8 ]
    label_filename: "particlenet_labels.txt"
  }
]